export default {
    ADD_USER: 'ADD_USER',
    REMOVE_USER: 'REMOVE_USER',
    ADD_ARTICLE: 'ADD_ARTICLE',
    REMOVE_ARTICLE: 'REMOVE_ARTICLE',
    ADD_TAG: 'ADD_TAG',
    REMOVE_TAG: 'REMOVE_TAG',
    ADD_COMMENT: 'ADD_COMMENT',
    REMOVE_COMMENT: 'REMOVE_COMMENT',
}
