export const ADD_ARTICLE = 'ADD_ARTICLE';
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_USER = 'ADD_USER';
export const ADD_TAG = 'ADD_TAG';
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';
export const GET_PROFILE = 'GET_PROFILE';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const REMOVE_TAG = 'REMOVE_TAG';
export const REMOVE_PROFILE = 'REMOVE_PROFILE';
export const REMOVE_USER = 'REMOVE_USER';
export const UPDATE_PROFILE = 'GET_PROFILE';

